FROM node:20.9.0-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY swagger.json .
COPY package.json .
RUN npm install

RUN npm install -g nodemon

# Bundle app source
COPY index.js ./

# Exports
EXPOSE 3000
CMD [ "npm", "run", "start.dev" ]